{% set name = "bioformats_jar" %}
{% set version = "2020.5.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 36f9842ea5680f8f645a20195ab57c869db6a0cbe56dfd2729c6fd6bc07bfe29

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - scyjava

test:
  imports:
    - bioformats_jar
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tlambert03/bioformats_jar
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: bioformats_package.jar, with type stubs and simple jpype wrapper
  doc_url: https://github.com/tlambert03/bioformats_jar
  dev_url: https://github.com/tlambert03/bioformats_jar

extra:
  recipe-maintainers:
    - tlambert03
